on:
  push:
    branches:
      - "firstProject"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        working-directory: ./greenbattery
        run: |
          npm install
          npm run build

      - name: Push file into s3W
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./greenbattery/build
          AWS_REGION: "ap-southeast-2"
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
