on:
  push:
    branches:
      - "firstProject"
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Build the app
        working-directory: ./greenbattery
        run: |
          npm ci
          npm run-script build

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Copy to s3
        run: |
          aws s3 cp ./greenbattery/build s3://testfrontendforgreenbattery --recursive
          aws s3api get-bucket-website --bucket testfrontendforgreenbattery --output text
